Fix ISO release build failures

diff --git a/external/gpl3/gcc/lib/libstdc++-v3/include/Makefile b/external/gpl3/gcc/lib/libstdc++-v3/include/Makefile
--- a/external/gpl3/gcc/lib/libstdc++-v3/include/Makefile
+++ b/external/gpl3/gcc/lib/libstdc++-v3/include/Makefile
@@ -8,6 +8,8 @@ SUBDIR+=	tr1 tr2
 
 .include "${.CURDIR}/../arch/${GCC_MACHINE_ARCH}/defs.mk"
 
+PAX?=${TOOL_PAX}
+
 .cc: # disable .cc->NULL transform
 
 DIST=		${GCCDIST}
@@ -27,6 +29,35 @@ INCSDIR=	/usr/include/g++
 #.PATH: ${DIST}/libstdc++-v3/include/c_compatibility
 .PATH: ${DIST}/libstdc++-v3/include/c_global
 .PATH: ${DIST}/libstdc++-v3/include/std
+
+afterinstall:
+	${RUN} set -eu; cd ${DESTDIR}/usr/include; \
+	if [ -L g++ ]; then \
+		rm -f g++; \
+	fi; \
+	if [ -d g++ ]; then \
+		if [ ! -d c++ ]; then \
+			mv g++ c++; \
+		else \
+			( cd g++ && ${PAX} -rw -pe . ../c++ ); \
+			rm -rf g++; \
+		fi; \
+	fi; \
+	if [ ! -d c++ ]; then \
+		echo "libstdc++ headers missing: expected c++ include directory" >&2; \
+		exit 1; \
+	fi; \
+	rm -rf g++; \
+	( cd c++ && find . -type d -print ) | \
+	while IFS= read -r d; do \
+		[ "$$d" = "" ] && continue; \
+		target=$${d#./}; \
+		${INSTALL_DIR} ${DESTDIR}/usr/include/g++/$${target:-.}; \
+	done; \
+	${INSTALL_DIR} ${DESTDIR}/usr/include/g++/profile; \
+	${INSTALL_DIR} ${DESTDIR}/usr/include/g++/profile/impl; \
+		${INSTALL_DIR} ${DESTDIR}/usr/include/g++/tr2; \
+	( cd c++ && ${PAX} -rw -pe . ../g++ )
 
 # Get default targets including <bsd.inc.mk>.
 .include <bsd.prog.mk>
